// flow-typed signature: 0c2477ab919f9be94a93974e6c1957ca
// flow-typed version: <<STUB>>/haul-cli_v^0.5.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'haul-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'haul-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'haul-cli/bin/cli' {
  declare module.exports: any;
}

declare module 'haul-cli/flow-typed/npm/express_v4.x.x' {
  declare module.exports: any;
}

declare module 'haul-cli/flow-typed/npm/jest_v19.x.x' {
  declare module.exports: any;
}

declare module 'haul-cli/src/cli' {
  declare module.exports: any;
}

declare module 'haul-cli/src/cliEntry' {
  declare module.exports: any;
}

declare module 'haul-cli/src/commands/bundle' {
  declare module.exports: any;
}

declare module 'haul-cli/src/commands/init' {
  declare module.exports: any;
}

declare module 'haul-cli/src/commands/start' {
  declare module.exports: any;
}

declare module 'haul-cli/src/errors' {
  declare module.exports: any;
}

declare module 'haul-cli/src/loaders/assetLoader' {
  declare module.exports: any;
}

declare module 'haul-cli/src/logger' {
  declare module.exports: any;
}

declare module 'haul-cli/src/messages/bundleBuilding' {
  declare module.exports: any;
}

declare module 'haul-cli/src/messages/bundleBuilt' {
  declare module.exports: any;
}

declare module 'haul-cli/src/messages/bundleFailed' {
  declare module.exports: any;
}

declare module 'haul-cli/src/messages/checkingProject' {
  declare module.exports: any;
}

declare module 'haul-cli/src/messages/commandFailed' {
  declare module.exports: any;
}

declare module 'haul-cli/src/messages/commandNotImplemented' {
  declare module.exports: any;
}

declare module 'haul-cli/src/messages/commandSuccess' {
  declare module.exports: any;
}

declare module 'haul-cli/src/messages/enterEntryFileName' {
  declare module.exports: any;
}

declare module 'haul-cli/src/messages/generatedConfig' {
  declare module.exports: any;
}

declare module 'haul-cli/src/messages/generatingConfig' {
  declare module.exports: any;
}

declare module 'haul-cli/src/messages/gitAddedEntries' {
  declare module.exports: any;
}

declare module 'haul-cli/src/messages/gitAddingEntries' {
  declare module.exports: any;
}

declare module 'haul-cli/src/messages/gitAlreadyAdded' {
  declare module.exports: any;
}

declare module 'haul-cli/src/messages/gitNotFound' {
  declare module.exports: any;
}

declare module 'haul-cli/src/messages/haulCommandHelp' {
  declare module.exports: any;
}

declare module 'haul-cli/src/messages/haulHelp' {
  declare module.exports: any;
}

declare module 'haul-cli/src/messages/index' {
  declare module.exports: any;
}

declare module 'haul-cli/src/messages/initialBundleInformation' {
  declare module.exports: any;
}

declare module 'haul-cli/src/messages/initialStartInformation' {
  declare module.exports: any;
}

declare module 'haul-cli/src/messages/invalidProject' {
  declare module.exports: any;
}

declare module 'haul-cli/src/messages/overwriteConfig' {
  declare module.exports: any;
}

declare module 'haul-cli/src/messages/selectEntryFile' {
  declare module.exports: any;
}

declare module 'haul-cli/src/messages/sourceMapFileNotFound' {
  declare module.exports: any;
}

declare module 'haul-cli/src/messages/sourceMapInvalidFormat' {
  declare module.exports: any;
}

declare module 'haul-cli/src/messages/verifiedProject' {
  declare module.exports: any;
}

declare module 'haul-cli/src/messages/webpackConfigNotFound' {
  declare module.exports: any;
}

declare module 'haul-cli/src/resolvers/AssetResolver' {
  declare module.exports: any;
}

declare module 'haul-cli/src/resolvers/HasteResolver' {
  declare module.exports: any;
}

declare module 'haul-cli/src/server/assets/debuggerWorker' {
  declare module.exports: any;
}

declare module 'haul-cli/src/server/index' {
  declare module.exports: any;
}

declare module 'haul-cli/src/server/middleware/devToolsMiddleware' {
  declare module.exports: any;
}

declare module 'haul-cli/src/server/middleware/liveReloadMiddleware' {
  declare module.exports: any;
}

declare module 'haul-cli/src/server/middleware/loggerMiddleware' {
  declare module.exports: any;
}

declare module 'haul-cli/src/server/middleware/missingBundleMiddleware' {
  declare module.exports: any;
}

declare module 'haul-cli/src/server/middleware/rawBodyMiddleware' {
  declare module.exports: any;
}

declare module 'haul-cli/src/server/middleware/statusPageMiddleware' {
  declare module.exports: any;
}

declare module 'haul-cli/src/server/middleware/symbolicateMiddleware' {
  declare module.exports: any;
}

declare module 'haul-cli/src/server/middleware/systraceMiddleware' {
  declare module.exports: any;
}

declare module 'haul-cli/src/server/util/WebsocketProxy' {
  declare module.exports: any;
}

declare module 'haul-cli/src/types' {
  declare module.exports: any;
}

declare module 'haul-cli/src/utils/exec' {
  declare module.exports: any;
}

declare module 'haul-cli/src/utils/findProvidesModule' {
  declare module.exports: any;
}

declare module 'haul-cli/src/utils/fixRequireIssues' {
  declare module.exports: any;
}

declare module 'haul-cli/src/utils/getBabelConfig' {
  declare module.exports: any;
}

declare module 'haul-cli/src/utils/makeReactNativeConfig' {
  declare module.exports: any;
}

declare module 'haul-cli/src/utils/polyfillEnvironment' {
  declare module.exports: any;
}

declare module 'haul-cli/vendor/polyfills/Array.es6' {
  declare module.exports: any;
}

declare module 'haul-cli/vendor/polyfills/Array.prototype.es6' {
  declare module.exports: any;
}

declare module 'haul-cli/vendor/polyfills/babelHelpers' {
  declare module.exports: any;
}

declare module 'haul-cli/vendor/polyfills/console' {
  declare module.exports: any;
}

declare module 'haul-cli/vendor/polyfills/error-guard' {
  declare module.exports: any;
}

declare module 'haul-cli/vendor/polyfills/Number.es6' {
  declare module.exports: any;
}

declare module 'haul-cli/vendor/polyfills/Object.es6' {
  declare module.exports: any;
}

declare module 'haul-cli/vendor/polyfills/Object.es7' {
  declare module.exports: any;
}

declare module 'haul-cli/vendor/polyfills/String.prototype.es6' {
  declare module.exports: any;
}

// Filename aliases
declare module 'haul-cli/bin/cli.js' {
  declare module.exports: $Exports<'haul-cli/bin/cli'>;
}
declare module 'haul-cli/flow-typed/npm/express_v4.x.x.js' {
  declare module.exports: $Exports<'haul-cli/flow-typed/npm/express_v4.x.x'>;
}
declare module 'haul-cli/flow-typed/npm/jest_v19.x.x.js' {
  declare module.exports: $Exports<'haul-cli/flow-typed/npm/jest_v19.x.x'>;
}
declare module 'haul-cli/src/cli.js' {
  declare module.exports: $Exports<'haul-cli/src/cli'>;
}
declare module 'haul-cli/src/cliEntry.js' {
  declare module.exports: $Exports<'haul-cli/src/cliEntry'>;
}
declare module 'haul-cli/src/commands/bundle.js' {
  declare module.exports: $Exports<'haul-cli/src/commands/bundle'>;
}
declare module 'haul-cli/src/commands/init.js' {
  declare module.exports: $Exports<'haul-cli/src/commands/init'>;
}
declare module 'haul-cli/src/commands/start.js' {
  declare module.exports: $Exports<'haul-cli/src/commands/start'>;
}
declare module 'haul-cli/src/errors.js' {
  declare module.exports: $Exports<'haul-cli/src/errors'>;
}
declare module 'haul-cli/src/loaders/assetLoader.js' {
  declare module.exports: $Exports<'haul-cli/src/loaders/assetLoader'>;
}
declare module 'haul-cli/src/logger.js' {
  declare module.exports: $Exports<'haul-cli/src/logger'>;
}
declare module 'haul-cli/src/messages/bundleBuilding.js' {
  declare module.exports: $Exports<'haul-cli/src/messages/bundleBuilding'>;
}
declare module 'haul-cli/src/messages/bundleBuilt.js' {
  declare module.exports: $Exports<'haul-cli/src/messages/bundleBuilt'>;
}
declare module 'haul-cli/src/messages/bundleFailed.js' {
  declare module.exports: $Exports<'haul-cli/src/messages/bundleFailed'>;
}
declare module 'haul-cli/src/messages/checkingProject.js' {
  declare module.exports: $Exports<'haul-cli/src/messages/checkingProject'>;
}
declare module 'haul-cli/src/messages/commandFailed.js' {
  declare module.exports: $Exports<'haul-cli/src/messages/commandFailed'>;
}
declare module 'haul-cli/src/messages/commandNotImplemented.js' {
  declare module.exports: $Exports<'haul-cli/src/messages/commandNotImplemented'>;
}
declare module 'haul-cli/src/messages/commandSuccess.js' {
  declare module.exports: $Exports<'haul-cli/src/messages/commandSuccess'>;
}
declare module 'haul-cli/src/messages/enterEntryFileName.js' {
  declare module.exports: $Exports<'haul-cli/src/messages/enterEntryFileName'>;
}
declare module 'haul-cli/src/messages/generatedConfig.js' {
  declare module.exports: $Exports<'haul-cli/src/messages/generatedConfig'>;
}
declare module 'haul-cli/src/messages/generatingConfig.js' {
  declare module.exports: $Exports<'haul-cli/src/messages/generatingConfig'>;
}
declare module 'haul-cli/src/messages/gitAddedEntries.js' {
  declare module.exports: $Exports<'haul-cli/src/messages/gitAddedEntries'>;
}
declare module 'haul-cli/src/messages/gitAddingEntries.js' {
  declare module.exports: $Exports<'haul-cli/src/messages/gitAddingEntries'>;
}
declare module 'haul-cli/src/messages/gitAlreadyAdded.js' {
  declare module.exports: $Exports<'haul-cli/src/messages/gitAlreadyAdded'>;
}
declare module 'haul-cli/src/messages/gitNotFound.js' {
  declare module.exports: $Exports<'haul-cli/src/messages/gitNotFound'>;
}
declare module 'haul-cli/src/messages/haulCommandHelp.js' {
  declare module.exports: $Exports<'haul-cli/src/messages/haulCommandHelp'>;
}
declare module 'haul-cli/src/messages/haulHelp.js' {
  declare module.exports: $Exports<'haul-cli/src/messages/haulHelp'>;
}
declare module 'haul-cli/src/messages/index.js' {
  declare module.exports: $Exports<'haul-cli/src/messages/index'>;
}
declare module 'haul-cli/src/messages/initialBundleInformation.js' {
  declare module.exports: $Exports<'haul-cli/src/messages/initialBundleInformation'>;
}
declare module 'haul-cli/src/messages/initialStartInformation.js' {
  declare module.exports: $Exports<'haul-cli/src/messages/initialStartInformation'>;
}
declare module 'haul-cli/src/messages/invalidProject.js' {
  declare module.exports: $Exports<'haul-cli/src/messages/invalidProject'>;
}
declare module 'haul-cli/src/messages/overwriteConfig.js' {
  declare module.exports: $Exports<'haul-cli/src/messages/overwriteConfig'>;
}
declare module 'haul-cli/src/messages/selectEntryFile.js' {
  declare module.exports: $Exports<'haul-cli/src/messages/selectEntryFile'>;
}
declare module 'haul-cli/src/messages/sourceMapFileNotFound.js' {
  declare module.exports: $Exports<'haul-cli/src/messages/sourceMapFileNotFound'>;
}
declare module 'haul-cli/src/messages/sourceMapInvalidFormat.js' {
  declare module.exports: $Exports<'haul-cli/src/messages/sourceMapInvalidFormat'>;
}
declare module 'haul-cli/src/messages/verifiedProject.js' {
  declare module.exports: $Exports<'haul-cli/src/messages/verifiedProject'>;
}
declare module 'haul-cli/src/messages/webpackConfigNotFound.js' {
  declare module.exports: $Exports<'haul-cli/src/messages/webpackConfigNotFound'>;
}
declare module 'haul-cli/src/resolvers/AssetResolver.js' {
  declare module.exports: $Exports<'haul-cli/src/resolvers/AssetResolver'>;
}
declare module 'haul-cli/src/resolvers/HasteResolver.js' {
  declare module.exports: $Exports<'haul-cli/src/resolvers/HasteResolver'>;
}
declare module 'haul-cli/src/server/assets/debuggerWorker.js' {
  declare module.exports: $Exports<'haul-cli/src/server/assets/debuggerWorker'>;
}
declare module 'haul-cli/src/server/index.js' {
  declare module.exports: $Exports<'haul-cli/src/server/index'>;
}
declare module 'haul-cli/src/server/middleware/devToolsMiddleware.js' {
  declare module.exports: $Exports<'haul-cli/src/server/middleware/devToolsMiddleware'>;
}
declare module 'haul-cli/src/server/middleware/liveReloadMiddleware.js' {
  declare module.exports: $Exports<'haul-cli/src/server/middleware/liveReloadMiddleware'>;
}
declare module 'haul-cli/src/server/middleware/loggerMiddleware.js' {
  declare module.exports: $Exports<'haul-cli/src/server/middleware/loggerMiddleware'>;
}
declare module 'haul-cli/src/server/middleware/missingBundleMiddleware.js' {
  declare module.exports: $Exports<'haul-cli/src/server/middleware/missingBundleMiddleware'>;
}
declare module 'haul-cli/src/server/middleware/rawBodyMiddleware.js' {
  declare module.exports: $Exports<'haul-cli/src/server/middleware/rawBodyMiddleware'>;
}
declare module 'haul-cli/src/server/middleware/statusPageMiddleware.js' {
  declare module.exports: $Exports<'haul-cli/src/server/middleware/statusPageMiddleware'>;
}
declare module 'haul-cli/src/server/middleware/symbolicateMiddleware.js' {
  declare module.exports: $Exports<'haul-cli/src/server/middleware/symbolicateMiddleware'>;
}
declare module 'haul-cli/src/server/middleware/systraceMiddleware.js' {
  declare module.exports: $Exports<'haul-cli/src/server/middleware/systraceMiddleware'>;
}
declare module 'haul-cli/src/server/util/WebsocketProxy.js' {
  declare module.exports: $Exports<'haul-cli/src/server/util/WebsocketProxy'>;
}
declare module 'haul-cli/src/types.js' {
  declare module.exports: $Exports<'haul-cli/src/types'>;
}
declare module 'haul-cli/src/utils/exec.js' {
  declare module.exports: $Exports<'haul-cli/src/utils/exec'>;
}
declare module 'haul-cli/src/utils/findProvidesModule.js' {
  declare module.exports: $Exports<'haul-cli/src/utils/findProvidesModule'>;
}
declare module 'haul-cli/src/utils/fixRequireIssues.js' {
  declare module.exports: $Exports<'haul-cli/src/utils/fixRequireIssues'>;
}
declare module 'haul-cli/src/utils/getBabelConfig.js' {
  declare module.exports: $Exports<'haul-cli/src/utils/getBabelConfig'>;
}
declare module 'haul-cli/src/utils/makeReactNativeConfig.js' {
  declare module.exports: $Exports<'haul-cli/src/utils/makeReactNativeConfig'>;
}
declare module 'haul-cli/src/utils/polyfillEnvironment.js' {
  declare module.exports: $Exports<'haul-cli/src/utils/polyfillEnvironment'>;
}
declare module 'haul-cli/vendor/polyfills/Array.es6.js' {
  declare module.exports: $Exports<'haul-cli/vendor/polyfills/Array.es6'>;
}
declare module 'haul-cli/vendor/polyfills/Array.prototype.es6.js' {
  declare module.exports: $Exports<'haul-cli/vendor/polyfills/Array.prototype.es6'>;
}
declare module 'haul-cli/vendor/polyfills/babelHelpers.js' {
  declare module.exports: $Exports<'haul-cli/vendor/polyfills/babelHelpers'>;
}
declare module 'haul-cli/vendor/polyfills/console.js' {
  declare module.exports: $Exports<'haul-cli/vendor/polyfills/console'>;
}
declare module 'haul-cli/vendor/polyfills/error-guard.js' {
  declare module.exports: $Exports<'haul-cli/vendor/polyfills/error-guard'>;
}
declare module 'haul-cli/vendor/polyfills/Number.es6.js' {
  declare module.exports: $Exports<'haul-cli/vendor/polyfills/Number.es6'>;
}
declare module 'haul-cli/vendor/polyfills/Object.es6.js' {
  declare module.exports: $Exports<'haul-cli/vendor/polyfills/Object.es6'>;
}
declare module 'haul-cli/vendor/polyfills/Object.es7.js' {
  declare module.exports: $Exports<'haul-cli/vendor/polyfills/Object.es7'>;
}
declare module 'haul-cli/vendor/polyfills/String.prototype.es6.js' {
  declare module.exports: $Exports<'haul-cli/vendor/polyfills/String.prototype.es6'>;
}
